title: Joe Nyland
author: Joe Nyland
description: I'm a developer, geek, mountain biker and dog lover from Northwich, UK and this is my site!
url: https://joenyland.github.io
markdown: kramdown
sass:
  style: compressed
