# Site settings
title: Joe Nyland
email: contact@joenyland.me
author: Joe Nyland
description: >
  I'm a developer, geek, mountain biker and dog lover from Warrington, UK and this is my web site!
blog:
  description: >
    Hey, I'm Joe Nyland and this is my blog!
    I'll try to write about interesting things related to DevOps,
    coding, SysAdmin and other things that interest me as I fumble
    my way through life, laughing and learning along the way.
    I can't guarantee that everything will be interesting, but I'll try!
baseurl: ""
blog_url: "http://blog.joenyland.me"
url: "http://joenyland.me"
twitter_username: JoeNyland
github_username:  MasterRoot24
exclude: ['README.md','LICENSE','CNAME','Gemfile','Gemfile.lock']
assets: "/assets"
nav_title: JoeNyland.me
permalink: /blog/:title/

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

sass:
    style: compressed
