# Site settings
title: Joe Nyland
email: contact@joenyland.me
description:
baseurl: ""
blog_url: "http://blog.joenyland.me"
url: "http://joenyland.me"
twitter_username: JoeNyland
github_username:  MasterRoot24
exclude: ['README.md','LICENSE','CNAME','Gemfile','Gemfile.lock']
assets: "/assets"
nav_title: JoeNyland.me
permalink: pretty

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
