# Site settings
title: JoeNyland.me
email: contact@joenyland.me
description: ""
baseurl: ""
url: "http://joenyland.me/"
github_username:  joenyland

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ''
      type: 'post'
    values:
      category: 'blog'
